import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface AuditReportData {
  title: string;
  subtitle: string;
  reportCode: string;
  generatedBy: string;
  generatedAt: string;
  period: string;
  propertyFilter: string;
  asOnDate?: string;
  headers: string[];
  rows: (string | number)[][];
  summaryRows?: { label: string; value: string | number; colSpan?: number }[];
  notes?: string[];
}

/**
 * Generates and downloads a styled Excel (.xlsx) file with Dream Dwell company metadata, headers, rows, and summary totals.
 */
export function exportToExcel(report: AuditReportData, filename?: string) {
  const wb = XLSX.utils.book_new();

  // Construct worksheet rows with header metadata
  const sheetData: any[][] = [
    ['DREAM DWELL ASSET MANAGEMENT INC. (CANADA)'],
    ['INTERNAL FINANCIAL MANAGEMENT & ACCOUNTING REPORT'],
    [`Report Title: ${report.title}`],
    [`Report Reference: ${report.reportCode}`],
    [`Reporting Period / As On: ${report.period}${report.asOnDate ? ` (As on: ${report.asOnDate})` : ''}`],
    [`Property Scope: ${report.propertyFilter}`],
    [`Generated By: ${report.generatedBy} on ${report.generatedAt}`],
    ['Accounting Standard: Canadian ASPE / IFRS Real Estate Accounting (CAD)'],
    ['Confidentiality: STRICTLY INTERNAL — DREAM DWELL FINANCE & TREASURY'],
    [], // Blank line
    report.headers,
    ...report.rows,
  ];

  if (report.summaryRows && report.summaryRows.length > 0) {
    sheetData.push([]);
    report.summaryRows.forEach((sr) => {
      sheetData.push([sr.label, sr.value]);
    });
  }

  if (report.notes && report.notes.length > 0) {
    sheetData.push([]);
    sheetData.push(['FINANCIAL NOTES & RECONCILIATION DISCLOSURES:']);
    report.notes.forEach((n) => sheetData.push([n]));
  }

  const ws = XLSX.utils.aoa_to_sheet(sheetData);

  // Auto column widths calculation
  const colWidths = report.headers.map((h, i) => {
    let maxLen = h.length;
    report.rows.forEach((row) => {
      const val = row[i] !== undefined && row[i] !== null ? String(row[i]) : '';
      if (val.length > maxLen) maxLen = val.length;
    });
    return { wch: Math.min(Math.max(maxLen + 4, 12), 45) };
  });
  ws['!cols'] = [{ wch: 25 }, ...colWidths];

  XLSX.utils.book_append_sheet(wb, ws, report.reportCode.slice(0, 31));

  const safeFilename = filename || `${report.reportCode}_${new Date().toISOString().slice(0, 10)}.xlsx`;
  XLSX.writeFile(wb, safeFilename);
}

/**
 * Generates and downloads a multi-sheet Master Financial Package (.xlsx) containing all financial schedules.
 */
export function exportMasterAuditExcelPackage(
  reports: AuditReportData[],
  filename = `DreamDwell_Consolidated_Financial_Dossier_${new Date().toISOString().slice(0, 10)}.xlsx`
) {
  const wb = XLSX.utils.book_new();

  // 1. Executive Summary Sheet
  const summarySheetData: any[][] = [
    ['DREAM DWELL ASSET MANAGEMENT INC. (CANADA)'],
    ['CONSOLIDATED INTERNAL FINANCIAL DOSSIER'],
    [`Generated Date: ${new Date().toLocaleString()}`],
    ['Accounting Standard: Canadian ASPE / IFRS Real Estate Accounting (CAD)'],
    [],
    ['Included Financial Schedules in this Dossier:'],
  ];

  reports.forEach((r, idx) => {
    summarySheetData.push([`${idx + 1}.`, r.reportCode, r.title, `Rows: ${r.rows.length}`]);
  });

  const summaryWs = XLSX.utils.aoa_to_sheet(summarySheetData);
  summaryWs['!cols'] = [{ wch: 6 }, { wch: 18 }, { wch: 45 }, { wch: 15 }];
  XLSX.utils.book_append_sheet(wb, summaryWs, 'Financial Overview');

  // 2. Individual Schedule Sheets
  reports.forEach((report) => {
    const sheetData: any[][] = [
      ['DREAM DWELL ASSET MANAGEMENT INC.'],
      [`Schedule: ${report.title} (${report.reportCode})`],
      [`Period: ${report.period} | Scope: ${report.propertyFilter}${report.asOnDate ? ` | As on: ${report.asOnDate}` : ''}`],
      [`Generated: ${report.generatedAt} by ${report.generatedBy}`],
      [],
      report.headers,
      ...report.rows,
    ];

    if (report.summaryRows) {
      sheetData.push([]);
      report.summaryRows.forEach((sr) => sheetData.push([sr.label, sr.value]));
    }

    const ws = XLSX.utils.aoa_to_sheet(sheetData);
    const colWidths = report.headers.map((h, i) => {
      let maxLen = h.length;
      report.rows.forEach((row) => {
        const val = row[i] !== undefined && row[i] !== null ? String(row[i]) : '';
        if (val.length > maxLen) maxLen = val.length;
      });
      return { wch: Math.min(Math.max(maxLen + 4, 12), 40) };
    });
    ws['!cols'] = [{ wch: 22 }, ...colWidths];

    const safeSheetName = report.reportCode.replace(/[^a-zA-Z0-9]/g, '').slice(0, 30);
    XLSX.utils.book_append_sheet(wb, ws, safeSheetName);
  });

  XLSX.writeFile(wb, filename);
}

/**
 * Generates and downloads an Executive Internal Financial PDF document with Dream Dwell navy & slate branding, tabular data, and formal controller sign-off.
 */
export function exportToPDF(report: AuditReportData, filename?: string) {
  const doc = new jsPDF({
    orientation: report.headers.length > 6 ? 'landscape' : 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // 1. Corporate Header Band - Deep Navy #0f172a
  doc.setFillColor(15, 23, 42); // Navy
  doc.rect(0, 0, pageWidth, 45, 'F');

  // Emerald/Teal accent stripe
  doc.setFillColor(13, 148, 136); // Teal #0d9488
  doc.rect(0, 45, pageWidth, 4, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('DREAM DWELL ASSET MANAGEMENT INC. (CANADA)', 40, 26);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.text('INTERNAL FINANCIAL MANAGEMENT & ACCOUNTS CONTROL REPORT', 40, 38);

  doc.setFontSize(8);
  doc.text(`Ref: ${report.reportCode}`, pageWidth - 40, 26, { align: 'right' });
  doc.text(`Generated: ${report.generatedAt}`, pageWidth - 40, 38, { align: 'right' });

  // 2. Report Details Header Box
  let yPos = 65;
  doc.setTextColor(30, 41, 59); // Slate-800
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text(report.title, 40, yPos);

  yPos += 14;
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(report.subtitle, 40, yPos);

  yPos += 16;
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(40, yPos, pageWidth - 80, 28, 4, 4, 'FD');

  doc.setFontSize(8);
  doc.setTextColor(51, 65, 85);
  doc.text(`Period / As-On: `, 50, yPos + 18);
  doc.setFont('helvetica', 'bold');
  doc.text(report.asOnDate ? `As on ${report.asOnDate} (${report.period})` : report.period, 125, yPos + 18);

  doc.setFont('helvetica', 'normal');
  doc.text(`Scope: `, 260, yPos + 18);
  doc.setFont('helvetica', 'bold');
  doc.text(report.propertyFilter, 295, yPos + 18);

  doc.setFont('helvetica', 'normal');
  doc.text(`Prepared By: `, 430, yPos + 18);
  doc.setFont('helvetica', 'bold');
  doc.text(report.generatedBy, 490, yPos + 18);

  yPos += 40;

  // 3. Render Table using jspdf-autotable
  const formattedRows = report.rows.map((row) => row.map((cell) => String(cell ?? '')));

  autoTable(doc, {
    startY: yPos,
    head: [report.headers],
    body: formattedRows,
    margin: { left: 40, right: 40 },
    theme: 'grid',
    styles: {
      fontSize: 7.5,
      cellPadding: 4.5,
      textColor: [30, 41, 59],
      lineColor: [226, 232, 240],
      lineWidth: 0.5,
    },
    headStyles: {
      fillColor: [15, 23, 42], // Dream Dwell Navy
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    didDrawPage: () => {
      // Footer on each page
      const footerY = pageHeight - 20;
      doc.setFontSize(7);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(148, 163, 184);
      doc.text('Strictly Confidential — Dream Dwell Asset Management Canada Internal Finance', 40, footerY);
      doc.text(
        `Page ${(doc as any).internal.getNumberOfPages()}`,
        pageWidth - 40,
        footerY,
        { align: 'right' }
      );
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 20;

  // Check if we need a new page for Financial Controller Sign-off
  if (finalY + 100 > pageHeight - 30) {
    doc.addPage();
    renderControllerSignOff(doc, 50, pageWidth);
  } else {
    renderControllerSignOff(doc, finalY, pageWidth);
  }

  const safeFilename = filename || `${report.reportCode}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(safeFilename);
}

function renderControllerSignOff(doc: jsPDF, y: number, pageWidth: number) {
  doc.setDrawColor(15, 23, 42);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(40, y, pageWidth - 80, 80, 4, 4, 'FD');

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('FINANCIAL CONTROLLER & TREASURY VERIFICATION ATTESTATION', 50, y + 16);

  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(
    'This internal financial statement has been reconciled against operating trust bank accounts, sub-metered utility bills, and general ledger journal postings under Canadian ASPE / IFRS standards.',
    50,
    y + 28,
    { maxWidth: pageWidth - 100 }
  );

  // Signature Lines
  const col1X = 50;
  const col2X = pageWidth / 2 + 10;

  doc.setFont('helvetica', 'bold');
  doc.text('Controller / Finance Lead: ______________________', col1X, y + 54);
  doc.text('Department: Treasury & Accounting', col1X, y + 68);

  doc.text('Signature: _________________________________', col2X, y + 54);
  doc.text('Date of Review: ______________________________', col2X, y + 68);
}
